<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Task;
use AppBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    /**
     * Delete Task.
     * @param Task $task
     */
    public function delete(Task $task)
    {
        $this->_em->remove($task);
        $this->_em->flush();
    }

    public function save(Task $task)
    {
        $this->_em->persist($task);
        $this->_em->flush();
    }

    /**
     * @param Task $task
     */
    public function refresh(Task $task)
    {
        $this->_em->refresh($task);
    }

    /**
     * @param $id
     * @param User $user
     * @return mixed
     */
    public function findOneByIdAndUser($id, User $user)
    {
        return $this->findOneBy([
            'id' => $id,
            'user' => $user,
        ]);
    }
}
